apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-compliance-nist-baseline
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-compliance-nist-baseline
        spec:
          remediationAction: inform
          severity: critical
          namespaceSelector:
            include: ["kube-system"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: nist-baseline-config
                  namespace: kube-system
