apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-platform-prod
  namespace: ocm-policies-prod
placementRef:
  name: shared-placement-prod
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: platform
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
