app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen: ':7007'
  auth:
    keys:
      - secret: ${BACKEND_SECRET}

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

organization:
  name: ${ORG_NAME}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  providers: {}

catalog:
  locations: []
