apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bu-workload-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rdgoarruda/gitops-bu.git'
    targetRevision: main
    path: overlays/prod
  destination:
    server: 'https://172.18.0.5:6443'
    namespace: apps
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
