apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocm-governance-nprod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - category: platform
          - category: security
          - category: observability
  template:
    metadata:
      name: 'ocm-policy-{{category}}-nprod'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rdgoarruda/gitops-global.git'
        targetRevision: main
        path: 'ocm-policies/governance/{{category}}/overlays/nprod'
      destination:
        server: https://kubernetes.default.svc
        namespace: ocm-policies-nprod
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
