apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocm-governance
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: nprod
                - env: prod
          - list:
              elements:
                - category: platform
                - category: security
                - category: observability
  template:
    metadata:
      name: 'ocm-policy-{{category}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rdgoarruda/gitops-global.git'
        targetRevision: main
        path: 'ocm-policies/governance/{{category}}/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ocm-policies-{{env}}'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
