apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-security-privileged-denial
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-security-privileged-denial
        spec:
          remediationAction: inform # Or enforce if desired
          severity: high
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-system", "open-cluster-management*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    security.kubernetes.io/enforce: privileged
