apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-platform-namespace-prod
  namespace: open-cluster-management
placementRef:
  name: placement-prod
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-platform-namespace
    kind: Policy
    apiGroup: policy.open-cluster-management.io
