apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bu-tools-nprod-a
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/rdgoarruda/gitops-bu-a.git'
              revision: main
              directories:
                - path: nprod/tools/*
          - list:
              elements:
                - cluster: nprod-bu-a
                  url: https://172.18.0.6:6443
  template:
    metadata:
      name: 'bu-a-tool-{{path.basename}}-nprod'
      labels:
        domain: bu-a
        environment: nprod
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rdgoarruda/gitops-bu-a.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {prune: true, selfHeal: true}
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
