apiVersion: policy.open-cluster-management.io/v1
kind: PolicySet
metadata:
  name: platform
spec:
  description: "Platform core policies (Namespaces, RBAC, etc.)"
  policies:
    - policy-platform-namespace
