apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: bu-b-placement-pr
  namespace: argocd
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            env: pr
            bu: bu-b
