apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bu-tools-ho-b
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/rdgoarruda/gitops-bu-b.git'
              revision: main
              directories:
                - path: ho/tools/*
          - clusters:
              selector:
                matchLabels:
                  bu: bu-b
                  env: ho
  template:
    metadata:
      name: 'bu-b-tool-{{path.basename}}-ho'
      labels:
        domain: bu-b
        environment: ho
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rdgoarruda/gitops-bu-b.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: default
      syncPolicy:
        automated: {prune: true, selfHeal: true}
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
