apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: shared-placement-prod
  namespace: ocm-policies-prod
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            env: prod
