apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-psa-restricted
  annotations:
    policy.open-cluster-management.io/standards: NIST-SP-800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-6 Configuration Settings
spec:
  remediationAction: inform # so detecta o desvio, nao corrige
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: config-psa-restricted
        spec:
          remediationAction: inform
          severity: high
          evaluationInterval:
            compliant: "10s"
            noncompliant: "10s"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: app-financeiro
                  labels:
                    pod-security.kubernetes.io/warn: restricted
