apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-compliance-nprod
  namespace: ocm-policies-nprod
placementRef:
  name: shared-placement-nprod
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: compliance
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet
