resources:
  - namespace.yaml
  - placement.yaml
  - clusterset-binding.yaml
  - binding-platform.yaml
  - binding-observability.yaml
  - binding-capacity.yaml
  - binding-security.yaml
  - binding-compliance.yaml
  - binding-infrastructure.yaml
