apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: bu-a-placement-pr
  namespace: ocm-policies-pr
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            env: pr
            bu: bu-a
